### ISSUE TITLE
Can no longer run test suite without all the plugins because of warnings

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4612]
This includes at least, doctestplus, asdf and remote-data

**Comment by dstansby** [comment]
Why is this an issue? Is there an instance where one would want to (or expect to) run the test suite without all the test dependencies?

**Comment by Cadair** [comment]
asdf is one of the things I wouldn't expect to have to be installed to run our tests, also we have code in conftest.py to handle a missing pytest-remotedata, so if that's not something we support anymore we should remove it.

**Comment by Cadair** [comment]
Also see [this](https://dev.azure.com/sunpy/sunpy/_build/results?buildId=10664&view=logs&j=6e7bd578-a810-548b-8fbf-8fa6b1a2d4f6&t=d1f04538-6627-58e5-ce9d-e142618c697c&l=61) fail on #4605 because you can't now run even the non-figure tests without pytest-mpl installed because we have some config option.

**Comment by nabobalis** [comment]
I guess my question is, what do we want to happen by default?

Do we want for pytest to skip over test that require these plugins (in the same manner want to skip over submodules without deps installed)?

**Comment by Cadair** [comment]
Maybe this is just expected, but it was jarring to me at least.

**Comment by nabobalis** [comment]
Sure I think it is a bit jarring to run non-figure tests and have it error since pytest-mpl isn't installed.

I just am unclear on what we would like to be the default behaviour.

**Comment by dstansby** [comment]
Can we just filter the appropriate warnings in `setup.cfg`?

**Comment by dstansby** [comment]
Pretty sure this was fixed in the above PR, feel free to re-open if not the case.

**Comment by Cadair** [comment]
Some of it but not all of it, I think it will still fail if asdf isn't installed, probably among others.

**Comment by dstansby** [comment]
I recently ran without asdf installed and it worked fine, and threw a warning at the end of the test run.
